# Generated by Django 5.1.6 on 2025-02-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('referance', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=255)),
                ('destignation', models.CharField(max_length=255)),
            ],
        ),
    ]
