# Generated by Django 5.1.6 on 2025-02-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='destination',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
